from . import test_high_risk_hca_inform_nurse_about_patient
from . import test_high_risk_nurse_informed_about_patient
from . import test_high_risk_inform_shift_coordinator
from . import test_high_risk_inform_medical_team
from . import test_high_risk_call_ambulance
