# -*- encoding: utf-8 -*-
{
    'name': 'Open e-Obs Lister Configuration',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Neova Health',
    'website': 'http://www.neovahealth.co.uk/',
    'depends': ['nh_eobs_mobile', 'nh_urinary_analysis', 'nh_neurovascular'],
    'data': ['data/lister_master_data.xml',
             'security/ir.model.access.csv',
             'security/ccot/ir.model.access.csv',
             'views/nh_eobs_lister_view.xml',
             'views/template.xml',
             'views/ccot_kanban.xml',
             'views/menuitem.xml',
             'views/obs_report.xml'],
    'demo': ['lister_user_data.xml'],
    'qweb': ['static/src/xml/nh_eobs_lister.xml'],
    'css': ['static/src/css/nh_eobs_lister.css'],
    'application': True,
    'installable': True,
    'active': False,
}